name: '${projectName}'
version: '${projectVersion}'
main: '${projectMainClass}'
load: STARTUP
api-version: 1.19
authors: [ CKATEPTb ]
description: Instances container with automatic annotation-based dependency injection.